### ISSUE TITLE
Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!

### ISSUE THREAD

**Issue by splaquet** [ddur/Warp-iMagick#8] opened 2023-05-03 21:40 UTC
I'm actually running into this error now, myself.

```
$ wp media regenerate --yes
Found 103 images to regenerate.
Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!
Lib::error: Wrong editor class selected: WP_Image_Editor_Imagick
Lib::error: Function get_warp_editor() returned an error: Wrong editor class selected: WP_Image_Editor_Imagick1/103 Regenerated thumbnails for "cropped-AD_Logo_4color.png" (ID 2528).
Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!
Lib::error: Wrong editor class selected: WP_Image_Editor_Imagick
Lib::error: Function get_warp_editor() returned an error: Wrong editor class selected: WP_Image_Editor_Imagick2/103 Regenerated thumbnails for "image" (ID 2527).
Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!
Lib::error: Wrong editor class selected: WP_Image_Editor_Imagick
Lib::error: Function get_warp_editor() returned an error: Wrong editor class selected: WP_Image_Editor_Imagick```

I looked into updating:
``` nano +486 warp-imagick/classes/class-shared.php```

but found that line 486 already had:
```				return new \WP_Error( 'warp-imagick', $msg );```

also, this error came up a few times:
```Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile```

i looked into the file, thinking that it might be one of our PDFs that we have within this media library... but it ended up being a pretty normal jpg image.

i tried installing a few additional png mods on the server, but that didn't seem to have any effect.

any suggestions?

...i almost forgot to mention, this is a WordOps webstack.  other than a few plugins, i'd like to believe that this install is quite identical to our other installs.

**Comment by ddur** [comment] 2023-05-04 20:07
**It could be a plugin conflict or new changes in wp media regenerate.**

Does regenerate work from web interface?

Test:
1) Enable wp-debug in wp-config.php
```// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );
```
2) deactivate and activate plugin. Is there any activation error?

3) Go to plugin settings page, refresh and check for messages.

4) regenerate one image and go back to 3)


**Some images may indeed have invalid metadata**

`libpng warning: iCCP: known incorrect sRGB profile

Warning Is not from plugin. Try to disable conversion to sRGB.

**Comment by ddur** [comment] 2023-05-04 20:21
Maybe this may help https://wordpress.org/support/topic/convert-rgb-to-srgb/

**Comment by ddur** [comment] 2023-05-04 21:15
I recently tested wp media regenerate for issue https://github.com/ddur/Warp-iMagick/issues/5, but couldn't reproduce the errors. Maybe I still have older version of WP-CLI.

**Comment by ddur** [comment] 2023-05-05 00:23
WP-CLI 2.5.0 works well, no errors. On PHP (cli) 7.4.

WP-CLI 2.7.0 generates weird errors.  On PHP (cli) 7.4.
It is much worse with PHP (cli) 8.2 which should be supported in latest WP-CLI version by now.

Do you have Performance Lab plugin activated? 
It is EXPERIMENTAL, REMOVE IT FROM YOUR SITES.

**Comment by ddur** [comment] 2023-05-05 15:36
@splaquet 

``libpng warning: iCCP: known incorrect sRGB profile``

Warning is probably not due to wrong ICC profile, but because of incompatibility with recent changes in WP-CLI.

I'm still investigating ...

**Comment by splaquet** [comment] 2023-05-05 18:22
here's my support ticket on Performance Lab plugin:
https://wordpress.org/support/topic/when-also-generate-jpeg-is-checked-off-in-media-existing-webps-serve-jpgs/

**Comment by splaquet** [comment] 2023-05-05 18:29
OH! ...but, I'd forgotten to mention that the `$ wp media regenerate --skip-delete --yes` seems to have worked.  or rather, it didn't kick out the bulk of those errors.

the PDFs kicked out errors... they can be ignored

`$ wp media regenerate --skip-delete --yes
Found 103 images to regenerate.
1/103 Regenerated thumbnails for "cropped-AD_Logo_4color.png" (ID 2528).
2/103 Regenerated thumbnails for "image" (ID 2527).
3/103 Regenerated thumbnails for "image" (ID 2526).
4/103 Regenerated thumbnails for "American Distilling logo" (ID 2525).
Warning: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421 (ID 2498)
Warning: Read error while retrieving metadata. (ID 2498)
5/103 Couldn't regenerate thumbnails for "AD Sell Sheet_Witch Hazel with Alcohol" (ID 2498).
Warning: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421 (ID 2497)
Warning: Read error while retrieving metadata. (ID 2497)
6/103 Couldn't regenerate thumbnails for "AD Sell Sheet_Witch Hazel Distillates" (ID 2497).
Warning: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421 (ID 2496)
Warning: Read error while retrieving metadata. (ID 2496)
7/103 Couldn't regenerate thumbnails for "AD Sell Sheet_Certified Organic" (ID 2496).
8/103 Regenerated thumbnails for "American Distilling" (ID 2449).
9/103 Regenerated thumbnails for "American Distilling logo" (ID 2414).
10/103 Regenerated thumbnails for "Witch Hazel" (ID 2378).
11/103 Regenerated thumbnails for "Witch Hazel" (ID 2353).
12/103 Regenerated thumbnails for "Witch Hazel" (ID 2351).
13/103 Regenerated thumbnails for "Witch Hazel" (ID 2318).
14/103 Regenerated thumbnails for "Witch Hazel" (ID 2306).
15/103 Regenerated thumbnails for "Witch Hazel" (ID 2304).
16/103 Regenerated thumbnails for "Witch Hazel" (ID 2299).
17/103 Regenerated thumbnails for "Witch Hazel" (ID 2295).
`

**Comment by ddur** [comment] 2023-05-05 19:41
In one ``wp media regenerate --yes`` test run, while active, "performance lab" plugin (I guess) renamed all thumbnails.jpeg to thumbnails.webp. That is not compatible with serving jpeg to older browsers. I deactivated it.

**Comment by splaquet** [comment] 2023-05-05 19:43
There’s a setting in Settings > Media to also keep jpeg files.  That’s where my issue was coming from, as I was *mostly* starting with webp images.

**Comment by ddur** [comment] 2023-05-05 19:50
Warp iMagick handles only uploaded JPEG/PNG media types. Has nothing to do with uploaded WebP or PDF media.

**Comment by ddur** [comment] 2023-05-05 20:06
AFAIK, WordPress already allows uploading WebP and (re)generating WebP thumbnails.  
I'm not sure if they know why&what they are doing.

**Comment by ddur** [comment] 2023-05-05 21:22
https://github.com/wp-cli/media-command/issues/149

I do not know if wp media regenerate ever added support for regenerating WebP media, issue is still open.

**Comment by ddur** [comment] 2023-05-07 10:23
@splaquet 


1) Latest  (2.7.1) ``wp media regenerate`` calls one filter twice, but that is handled in the way that **does not break anything**. So ``Lib::error: Regenerate wp_create_image_subsizes( _, $attachment_id ) argument mismatch!`` is OK as long as you **do not activate Performance Lab plugin**.  
I expect to fix/remove that error report in the next version update.

2) Errors
    ```
    Lib::error: Wrong editor class selected: WP_Image_Editor_Imagick
    Lib::error: Function get_warp_editor() returned an error: Wrong editor class selected: WP_Image_Editor_Imagick1/103 Regenerated thumbnails for "cropped-AD_Logo_4color.png" (ID 2528).
    ```
    are caused by **Performance Lab plugin** because it removes/overrides 'Warp_Image_Editor_Imagick', same as few other conflicting plugins. Anyways, **Performance Lab is not made to serve WebP images only to WebP enabled browsers, and something else (JPEG/PNG) to other browsers. All browsers always get the same image mime-type.**

**Comment by ddur** [comment] 2023-05-07 16:31
@splaquet 

As long you don't enable 

``[_] Enable Dominant Color Images.``
``[_] Enable WebP Uploads.``

rest of Performance Lab should work fine.

**Comment by ddur** [comment] 2023-05-10 08:32
Closing.

1) Error related to ``wp media regenerate``  (WP-CLI) is fixed an will be published with next update/release.

2) Errors related to Performance Lab plugin are moved to new issue: https://github.com/ddur/Warp-iMagick/issues/9

**Closed by ddur** 2023-05-10 08:32 UTC
Labels: wp media regenerate

**Comment by ddur** [comment] 2023-05-17 21:28
@splaquet 

Hi, I  have next version ready. Would you like to test it in your environment(s) before releasing?
If yes, do you mind if I contact you via your registered email ?

**Comment by ddur** [comment] 2023-07-14 07:30
@splaquet 
> OH! ...but, I'd forgotten to mention that the `$ wp media regenerate --skip-delete --yes` seems to have worked. or rather, it didn't kick out the bulk of those errors.

Here was more than one issue.
It should be working now without `--skip-delete`. See #12.

**Comment by ddur** [comment] 2023-07-14 08:22
@splaquet 

`libpng warning: iCCP: known incorrect sRGB profile`

Recently I got the same message on one specific PNG image. 

As far as I can tell, libpng warning (via php-gd),
is telling us that image has incorrect sRGB profile, 
but that incorrect profile is known/recognized by libpng.

> [It's because libpng 1.6 does more checking of the pngs, and one or more of the png files used has an old sRGB profile.](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#22747902)


Image is still regenerated without other errors/warnings. 
Nothing to do with Warp iMagick plugin or with `wp media regenerate` command.
