### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by splaquet** [ddur/Warp-iMagick#7] opened 2023-05-03 20:59 UTC
whenever i try and register for automatic updates, over at https://warp-imagick.pagespeed.club/, i'm unable to reset my password. it says that it's sending a reset email, but none have ever arrived.

just an FYI, as your wordpress SMTP plugin probably isn't Authenticated.

**Comment by ddur** [comment] 2023-05-04 20:47
I don't use SMTP plugin.
Email is sent from WordPress.
Other users are recently registered.

Did you check your spam folder?

**Comment by splaquet** [comment] 2023-05-05 18:26
yeah... I've checked.  I'm not finding anything 🙁

**Comment by ddur** [comment] 2023-05-05 22:28
@splaquet 

Looks like your email provider is very restrictive. 
I found other registration attempts from same provider that never activated account.

I guess that my self hosted email sender does not send DKIM/SPF headers.

Until issue is fixed, you may try with less restrictive email provider.

Thank you for letting me know!

**Comment by ddur** [comment] 2023-05-06 10:25
@splaquet 

Please try to reset your password again and let me know if it works now. :sunglasses:

**Comment by ddur** [comment] 2023-05-07 12:37
@splaquet 

I just witnessed user activation from same email provider.

Closing. Let me know if still doesn't work for you.

**Comment by splaquet** [comment] 2023-05-07 14:58
My work provider uses Barracuda. I signed up through that email. 

As a long time system admin for shared hosting, I've always had issues with Barracuda. Not even that they're saying we're on any RBL or anything of the sort, but that "we don't trust you".  

I pushed a reset and it did come though. Thank you!

**Comment by ddur** [comment] 2023-05-18 08:13
@splaquet 

> I pushed a reset and it did come though. Thank you!

As far as I can tell, problem was caused by domain owner of your email address. Now they have "[an offer they cant refuse](https://www.phrases.org.uk/meanings/an-offer-he-cant-refuse.html)" :sunglasses:

**Comment by splaquet** [comment] 2023-05-30 13:24
sorry mate, but it would appear that there's still an issue with the password reset form.

i didn't catch this at first, but just noticed that you say "Site doesn't use SMTP plugin. Email is sent from WordPress."

are you hosted on WordPress? if not, and/or if you're self hosted, you need to add an SMTP auth mechanism to your email sending.

here's a solid free one:
https://wordpress.org/plugins/post-smtp/

<img width="371" alt="image" src="https://github.com/ddur/Warp-iMagick/assets/6146508/f3f4d096-a220-4c14-8fd7-8849d459cd83">

one of the easier methods to figure out if you're 100% authenticated is through gmail.com.  

if you have an @gmail or Workspace email address: 
- send yourself an email from your website
- open the email
- click on the email/menu options toggle
- click on "view source" (i think?  it might be view original.. either way, it'll show you the email headers... that's what we want)
- (when you see the source) do a page search for "fail".  if you have anything pop up, at least 1 auth mechanism within your email isn't properly authenticated. (SPF, DKIM, DMARC, etc)
- if "fail" shows ZERO results, try searching for "pass".  (no FAILS = 3+ PASS results)

hopefully that helps!

**Comment by ddur** [comment] 2023-05-30 18:12
@splaquet 

Thank you for letting me know.

That is not same old issue but new one. :sunglasses: 

"Barracuda" :wink:  requires changing credentials every week. :disappointed: :disappointed_relieved:

**Comment by ddur** [comment] 2023-05-30 18:35
Or someone exceeded my sending limit.

**Comment by ddur** [comment] 2023-05-30 22:39
I have to abandon this "fix".

**Comment by ddur** [comment] 2023-05-31 07:26
Be aware:

Due to missing or insufficient anti-spam signatures,  GMail ignores emails sent from update server. 

That means no new registrations and no password resets for GMail users until this issue is fixed.

**Comment by splaquet** [comment] 2023-05-31 15:20
@ddur ... if you don't have an SMTP Auth plugin on your WP install, and/or your hosting provider doesn't send out authenticated emails on your behalf; i can pretty much guarantee & promise that adding that plugin will resolve your issue.

i manage a half dozen shared web servers, supporting several hundred end users.  as a system admin, i HAVE to block unauthenticated emails from sending out.  if i don't, any compromised account has the ability to send out hundreds of spam emails an hour.

the solution for them (and 99.99% of the population) is to install an SMTP Auth plugin.  

any RBL/spam blocker service is ONLY looking at proper PASS (not FAIL) responses on the key auth methods & domain reputation.

additionally, I'm a Google Workspace partner.  I can promise you that gmail does not require anti-spam signatures.  if you're concerned about how your domain is being score, https://postmaster.google.com is a GREAT resource to keep tabs on your sending score.

so, in review, unless you have one of the most unique WP installs out there, i'm willing to be that an SMTP Auth plugin is your solution.   ...just saying, as i have over a decade of experience in this area.  also worth noting, an SMTP Auth plugin is typically one of the first/required plugins that i install on any of my WP builds.

**Comment by ddur** [comment] 2023-06-01 07:59
@splaquet 

Thank you.

1) Meaning of what I named "anti-spam signature" is  (SPF, DKIM, DMARC, etc).
2) I have tried few SMTP plugins and I don't like ones advertising/promoting PRO version on my dashboard.

I have tested some plugins:

FluentSMTP looks like right candidate, but it's instructions for Gmail are wrong, redirecting to foreign domain. Gmail (maybe recently) requires ownership of redirected domain,

Gmail SMTP worked well. Eventually I discovered that main problem is Gmail, doing everything to limit/screw free accounts. I have no intention to pay emailing expenses for free plugin.

3) I'm not sure yet that I'm willing to publicly expose my internet provider domain along with it's country location. But that seems most likely free solution for now. Maybe I will be allowed to borrow someone else's provider mail. :sunglasses: 

4) I guess, configuring Postfix is right solution, but it was really hard to configure and I expect it will take somewhat longer time to add more verification signatures/headers. Further configuring Postfix (and domain records) is currently delayed for "later experience" :sunglasses: 

5) Thanks for the link, I will add it to my collection: 
http://www.open-spf.org/
https://www.dkim.org/
https://dmarc.org/
https://dmarcian.com/spf-syntax-table/

https://www.mail-tester.com/
https://www.emailchecky.com/en/
https://www.mailgenius.com/
https://appmaildev.com/en/dkim

6) I can't find SMTP Auth plugin on WordPress, do you have link or is gone in recent plugin repository cleansing by retiring bitch?

**Comment by ddur** [comment] 2023-06-03 09:01
@splaquet 

It should work now.

**Closed by ddur** 2023-06-03 09:01 UTC
Labels: update server issue, update server sending emails

**Comment by splaquet** [comment] 2023-06-03 12:26
> @splaquet 
> It should work now, again.

I was about to send you a disappointing message... But, even though the error message displayed, I noticed that a reset email DID come through. 

It'd been so long since starting this journey, I only realized/remembered now that I used my personal gmail email address to sign up. Not the company email with Barracuda protection. 

Thank you for your diligence!!! It's greatly appreciated 😃 

![image](https://github.com/ddur/Warp-iMagick/assets/6146508/1e915eb8-b4bf-4bdd-9888-faa61af6e515)

**Comment by ddur** [comment] 2023-06-03 14:17
I was shortly testing few other (failed) SMTP options. Maybe we did it on about same time, but I can't find other failed emails in the logs, than my tests. I just tried to reset my password, and all seems normal. Is it possible that you have old login page still in your browser cache?

**Comment by ddur** [comment] 2023-06-03 14:31
@splaquet 

[GMail SMTP doesn't work with normal authentication since May 30, 2022](https://support.mozilla.org/mk/questions/1369886#:~:text=Google%20has%20announced%20that%20after,will%20enable%202%2Dstep%20verification.) 

I can't find plugin in WP directory that is able to long term connect with GMail via OAuth2, like Mozilla Thunderbird does. 

Both [Fluent SMTP](https://wordpress.org/plugins/fluent-smtp/) and [GMail SMTP](https://wordpress.org/plugins/fluent-smtp/) stopped working after week or two.

**Comment by splaquet** [comment] 2023-06-03 16:32
The plugin I shared earlier, Post SMTP offers that in the free version.

**Comment by ddur** [comment] 2023-06-04 19:44
@splaquet 

> The plugin I shared earlier, Post SMTP offers that in the free version.

[Post SMTP plugin](https://wordpress.org/plugins/post-smtp/) requires same setup procedure at [Google Cloud Console](https://console.cloud.google.com/apis/dashboard), as the other two [Fluent SMTP](https://wordpress.org/plugins/fluent-smtp/) and [GMail SMTP](https://wordpress.org/plugins/gmail-smtp/). 

It is not problem in plugins, problem is that configured "cloud" application stops working after week or two, and/or requires manual client secret changes every week or two. That is unmaintainable and useless.

**Comment by ddur** [comment] 2023-06-04 19:50
I guess, Mozilla Thunderbird has their application published on paid Google account.
